BilleterieBundle\Entity\Billet:
    type: entity
    table: null
    repositoryClass: BilleterieBundle\Repository\BilletRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        date:
            type: datetime
        heureDeb:
            type: time
        heureFin:
            type: time
        lieu:
            type: string
            length: 255
    lifecycleCallbacks: {  }
