<?php

namespace BilleterieBundle\Repository;
Use Doctrine\ORM\EntityRepository;
/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends EntityRepository
{
       public function getAllDesc()
    {
        $query = $this->createQueryBuilder('a');
        $query->orderBy('a.id', 'DESC');

        return $query
            ->getQuery()
            ->getResult();

    }
}
